
services:
  postgres-db:
    image: postgres:15-alpine  # Lekka wersja bazy
    container_name: postgres
    ports:
      - "5432:5432" # Mapowanie portu: TwójKomputer:Kontener
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mtab_db
    volumes:
    - postgres_data:/var/lib/postgresql/data # Aby dane przetrwały restart kontenera

volumes:
  postgres_data: